apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: acm-observability-assistant-ns
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  serviceName: "ollama-service"
  template:
    metadata:
      labels:
        app: ollama
    spec:
      initContainers:
      - name: ollama-model-puller
        image: ollama/ollama
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Starting model pull..."
          ollama serve &
          PID=$!
          sleep 10
          echo "Pulling embedding model..."
          ollama pull nomic-embed-text
          echo "Model pull complete."
          kill $PID
        volumeMounts:
        - name: ollama-storage
          mountPath: /root
        env:
        - name: OLLAMA_MODELS
          value: "/root/.ollama"
        - name: HOME
          value: "/root"
      containers:
      - name: ollama
        image: ollama/ollama
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-storage
          mountPath: /root
        env:
        - name: OLLAMA_MODELS
          value: "/root/.ollama"
        - name: HOME
          value: "/root"
  volumeClaimTemplates:
  - metadata:
      name: ollama-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: acm-observability-assistant-ns
  labels:
    app: ollama
spec:
  ports:
  - port: 11434
    targetPort: 11434
  selector:
    app: ollama