# ---
# This ConfigMap holds the application's configuration.
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-observability-assistant-config
  namespace: acm-observability-assistant-ns
data:
  config.yaml: |
    llm_config:
      rewrite_model: "gemini/gemini-2.5-flash-lite-preview-06-17"
      answer_model: "gemini/gemini-2.5-flash"
      enable_faithfulness_check: true

    retriever_config:
      similarity_top_k: 12
      rerank_top_n: 5
      similarity_cutoff: 0.8

    embedding_config:
      model_name: "nomic-embed-text"
      ollama_host: "http://localhost:11434"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.grafana: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"acm-observability-assistant-route"}}'
  name: acm-observability-assistant-sa
  namespace: acm-observability-assistant-ns
---
# ---
# Note: Create this secret before applying the manifest.
# oc create secret generic litellm-api-keys -n acm-observability-assistant-ns --from-literal=GOOGLE_API_KEY='...'
# ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: acm-observability-assistant
  namespace: acm-observability-assistant-ns
  labels:
    app: acm-observability-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-observability-assistant
  serviceName: "acm-observability-assistant-service"
  template:
    metadata:
      labels:
        app: acm-observability-assistant
    spec:
      serviceAccountName: acm-observability-assistant-sa
      containers:
      - name: acm-observability-assistant
        image: quay.io/rh-ee-tmange/acm-observability-expert:latest
        command: ["chainlit", "run", "main.py", "--host", "0.0.0.0", "--port", "8000", "-w"]
        volumeMounts:
        - name: rag-storage
          mountPath: /app/storage
        - name: model-cache
          mountPath: /app/.cache
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        env:
        - name: OLLAMA_HOST
          value: "http://ollama-service:11434"
        # Set a writable cache directory for sentence-transformers
        - name: HF_HOME
          value: "/app"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: litellm-api-keys
              key: GEMINI_API_KEY
              optional: true
      - name: oauth-proxy
        image: quay.io/stolostron/origin-oauth-proxy:4.16
        args:
        - --provider=openshift
        - --openshift-service-account=acm-observability-assistant-sa
        - --upstream=http://localhost:8000 # Forwards to your app container on port 8080
        - --http-address=:8001 # The proxy listens on this port
        - --https-address= # only listen http
        - --cookie-secret=thisisasecret # Change this!
        ports:
        - containerPort: 8001
          name: oauth-proxy
      volumes:
      - name: config-volume
        configMap:
          name: acm-observability-assistant-config
  volumeClaimTemplates:
  - metadata:
      name: rag-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: model-cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi # Adjust as needed for the reranker model size
---
apiVersion: v1
kind: Service
metadata:
  name: acm-observability-assistant-proxy-service
  namespace: acm-observability-assistant-ns
spec:
  ports:
  - port: 443
    targetPort: 8001
  selector:
    app: acm-observability-assistant
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acm-observability-assistant-route
  namespace: acm-observability-assistant-ns
spec:
  to:
    kind: Service
    name: acm-observability-assistant-proxy-service
  subdomain: acm-observability-assistant
  tls:
    termination: edge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-observability-assistant-proxy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator # A default role that allows for token reviews
subjects:
- kind: ServiceAccount
  name: acm-observability-assistant-sa
  namespace: acm-observability-assistant-ns